/** Generated by mdsite CLI — do not edit */
module.exports = {
  title: "mdsite",
  repo_url: "https://github.com/kotulc/mdsite",
  feed_url: "updates",
  theme_toggle: "navbar",
  ingest_readme: false,
  toc: true,
  meta_sidebar: true,
  content_style: "",
  theme_mood: "",
  logo_seed: 1,
  flatten: ["updates"],
  nav_order: {"":["about","getting-started","configuration"],"features":["overview","components"],"specs":["format"],"updates":["welcome"]},
}
