/** Generated by mdsite CLI — do not edit */
module.exports = {
  title: "Graphly Example",
  repo_url: "",
  feed_url: "",
  description: "",
  footer: "",
  theme_toggle: "navbar",
  toc: true,
  meta_sidebar: true,
  reading_time: true,
  theme: {"color":"default","typeset":"sans","hue":{"light":212,"dark":204},"saturation":100,"font_stack":""},
  flatten: [],
  nav_order: {},
}
