/**
 * YAML config loader for the mdsite CLI.
 * Reads mdsite.yaml, validates required fields, applies defaults, and generates
 * site.config.js so Next.js and Nextra can consume the config at build time.
 */
const fs   = require('fs')
const path = require('path')
const yaml = require('js-yaml')
const { resolve_theme } = require('./theme')
const { FIELDS, METRICS } = require('./enrich')


const DEFAULTS = {
  repo_url:       '',
  feed_url:       '',
  description:    '',
  footer:         '',
  theme_toggle:   'navbar',
  toc:            true,
  reading_time:   true,
  theme:          { color: 'default', typeset: 'sans', navbar: '', footer: '' },
  enrich:         { url: '', fields: ['description', 'tags', 'categories'], metrics: [], strict: true },
  flatten:        [],
  nav_order:      {},
  content:        './docs',
  output:         './dist',
  components:     '',
  assets:         '',
}


function load_config(yaml_path) {
  /** Read and parse a YAML config file; resolve content/output relative to its directory. */
  const abs  = path.resolve(yaml_path)
  const dir  = path.dirname(abs)
  const raw  = yaml.load(fs.readFileSync(abs, 'utf8'))
  const cfg  = { ...DEFAULTS, ...raw }

  if (!cfg.title) throw new Error(`mdsite.yaml: 'title' is required`)

  cfg.theme  = resolve_theme({ ...DEFAULTS.theme, ...(raw.theme || {}) })
  cfg.enrich = validate_enrich({ ...DEFAULTS.enrich, ...(raw.enrich || {}) })

  cfg.content = path.resolve(dir, cfg.content)
  cfg.output  = path.resolve(dir, cfg.output)
  if (cfg.components) cfg.components = path.resolve(dir, cfg.components)
  if (cfg.assets)     cfg.assets     = path.resolve(dir, cfg.assets)

  return cfg
}


function validate_enrich(enrich) {
  /** Validate enrich.fields/metrics names against the routes known to scripts/enrich.js. */
  for (const f of enrich.fields) {
    if (!(f in FIELDS)) {
      throw new Error(`mdsite.yaml: unknown enrich.fields '${f}' (valid: ${Object.keys(FIELDS).join(', ')})`)
    }
  }
  for (const m of enrich.metrics) {
    if (!(m in METRICS)) {
      throw new Error(`mdsite.yaml: unknown enrich.metrics '${m}' (valid: ${Object.keys(METRICS).join(', ')})`)
    }
  }
  return enrich
}


function write_site_config(config, dest_dir) {
  /** Generate site.config.js from a config object for Next.js/Nextra consumption. */
  const dir  = dest_dir || path.join(__dirname, '..')
  const keys = [
    'title', 'repo_url', 'feed_url', 'description', 'footer',
    'theme_toggle', 'toc', 'reading_time',
    'theme', 'flatten', 'nav_order',
  ]
  const body = keys
    .map(k => `  ${k}: ${JSON.stringify(config[k])}`)
    .join(',\n')

  fs.writeFileSync(
    path.join(dir, 'site.config.js'),
    `/** Generated by mdsite CLI — do not edit */\nmodule.exports = {\n${body},\n}\n`
  )
}


module.exports = { load_config, write_site_config, DEFAULTS }
