/**
 * YAML config loader for the mdsite CLI.
 * Reads mdsite.yaml, validates required fields, applies defaults, and generates
 * site.config.js so Next.js and Nextra can consume the config at build time.
 */
const fs   = require('fs')
const path = require('path')
const yaml = require('js-yaml')


const DEFAULTS = {
  repo_url:       '',
  feed_url:       '',
  theme_toggle:   'navbar',
  toc:            true,
  meta_sidebar:   true,
  reading_time:   true,
  content_style:  '',
  theme_mood:     '',
  logo_seed:      1,
  flatten:        [],
  nav_order:      {},
  content:        './docs',
  output:         './dist',
  components:     '',
}


function load_config(yaml_path) {
  /** Read and parse a YAML config file; resolve content/output relative to its directory. */
  const abs  = path.resolve(yaml_path)
  const dir  = path.dirname(abs)
  const raw  = yaml.load(fs.readFileSync(abs, 'utf8'))
  const cfg  = { ...DEFAULTS, ...raw }

  if (!cfg.title) throw new Error(`mdsite.yaml: 'title' is required`)

  cfg.content = path.resolve(dir, cfg.content)
  cfg.output  = path.resolve(dir, cfg.output)
  if (cfg.components) cfg.components = path.resolve(dir, cfg.components)

  return cfg
}


function write_site_config(config, dest_dir) {
  /** Generate site.config.js from a config object for Next.js/Nextra consumption. */
  const dir  = dest_dir || path.join(__dirname, '..')
  const keys = [
    'title', 'repo_url', 'feed_url',
    'theme_toggle', 'toc', 'meta_sidebar', 'reading_time',
    'content_style', 'theme_mood', 'logo_seed', 'flatten', 'nav_order',
  ]
  const body = keys
    .map(k => `  ${k}: ${JSON.stringify(config[k])}`)
    .join(',\n')

  fs.writeFileSync(
    path.join(dir, 'site.config.js'),
    `/** Generated by mdsite CLI — do not edit */\nmodule.exports = {\n${body},\n}\n`
  )
}


module.exports = { load_config, write_site_config, DEFAULTS }
